test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -16,3 +16,7 @@ jobs:
         - name: Run test
           run: npm test
           continue-on-error: true
+        - if: ${{ steps.test.outputs.error != '' && !contains(steps.test.outputs.error, 'supabaseUrl is required') }}
+          run: |
+            echo '::error ::test failed with "${{ steps.test.outputs.error }}"'
+            exit 1
